# Generated by Django 3.0.11 on 2021-01-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created', verbose_name='Creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was modified', verbose_name='Modificado el')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=180, verbose_name='Descripción')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('product_type', models.CharField(max_length=50, verbose_name='Tipo Producto')),
                ('gross_price', models.FloatField(verbose_name='Precio Bruto')),
                ('price_neto', models.FloatField(verbose_name='Precio Neto')),
            ],
            options={
                'ordering': ['created', 'modified'],
                'get_latest_by': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
