# Generated by Django 3.0.11 on 2021-01-15 00:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=50, unique=True, verbose_name='DNI')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
                ('full_name', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='client_address')),
            ],
        ),
    ]
