# Generated by Django 3.0.11 on 2021-01-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created', verbose_name='Creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was modified', verbose_name='Modificado el')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('street', models.CharField(max_length=50, verbose_name='Calle')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client_Address')),
            ],
            options={
                'ordering': ['created', 'modified'],
                'get_latest_by': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
